---
# tasks file for debian12-k8s-work-node-setup

- name: ставим нужные пакеты
  apt:
    name: 
      -  curl 
      -  apt-transport-https
      -  ca-certificates 
      -  gnupg
    update_cache: yes 

- name: создаем директорую для ключей
  ansible.builtin.file:
    path: /etc/apt/keyrings 
    state: directory
    recurse: yes    
 
- name: добавялем ключ
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: меняем пермишены 
  file: dest=/etc/apt/keyrings/docker.asc mode=a+r

- name: добавим репу
  shell: 
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: ставим containerd
  apt:
    name: 
      -  containerd.io
    update_cache: yes 

- name: создадим директорую для containerd
  ansible.builtin.file:
    path: /etc/containerd 
    state: directory
    recurse: yes

- name: создадим конфиг
  shell: 
    cmd: containerd config default | tee /etc/containerd/config.toml

- name: включи SystemdCgroup in config  
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: перезапустим containerd
  systemd:
      name: containerd
      state: restarted

- name: создадим директорую для gpg ключа k8s
  shell:  curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: добавим репу для k8s 
  shell: 
    cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' |  tee /etc/apt/sources.list.d/kubernetes.list

- name: меняем пермишены для kubernetes.list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'

- name: ставим пакеты для k8s 
  apt:
    name: 
      -  kubeadm
#      -  kube-proxy 
      -  kubelet 
      -  kubectl 
      -  kubernetes-cni
      -  ethtool
      -  conntrack
    update_cache: yes  

- name: выключим своп
  shell: 
    cmd: swapoff -a

- name: выключим своп в /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'     

- name: добавим br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present    

- name: включим форвардинг
  replace:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'    

- name: включим форвардинг прямо сейчас
  shell: 
    cmd: sysctl -w net.ipv4.ip_forward=1

# надо ли ?
#- name: instal Flannel in k8s
#  shell: 
#    cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/v0.20.2/Documentation/kube-flannel.yml   