[servers]

[k8s]
k8smaster ansible_host=31.129.63.56  ansible_ssh_user=root  ansible_python_interpreter=/usr/bin/python3
k8work_node ansible_host=31.129.63.115  ansible_ssh_user=root  ansible_python_interpreter=/usr/bin/python3


