apiVersion: v1
kind: Service
metadata:
  name: auth-node-app
  namespace: nodeapp
spec:
  type: NodePort
  selector:
    app: auth-node-app
  ports:
    - name: https
      port: 30500
      targetPort: 30500
      nodePort: 30500
